In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("..")
import torch
from dnn_training.dataset_ak import *
from dnn_training.dataset_torch import *
import numpy as np
from dnn_training.trainer import *
import awkward as ak

In [2]:
model, loss = makeModelLoss()
trainer = Trainer(model, loss_fn=loss, device="cpu", log_output="/grid_mnt/data_cms_upgrade/cuisset/supercls/dnn_training/test")
trainer.reloadModel("/grid_mnt/data_cms_upgrade/cuisset/supercls/dnn_training/full/Mar26_16-31-15/model_epoch140.pth")

In [3]:
train_dataset, val_dataset = makeDatasetsTrainVal("/grid_mnt/data_cms_upgrade/cuisset/supercls/alessandro_electrons/supercls-v13/superclsDumper_*.root", device="cpu")

In [6]:
trainer.current_epoch = 0
trainer.val_loop(DataLoader(val_dataset, batch_size=100000), val_dataset)

/grid_mnt/data_cms_upgrade/cuisset/conda/envs/ticlRegression-gpu/lib/python3.11/site-packages/sklearn/metrics/_ranking.py:1137: UndefinedMetricWarning: No negative samples in y_true, false positive value should be meaningless
  warnings.warn(
/grid_mnt/data_cms_upgrade/cuisset/conda/envs/ticlRegression-gpu/lib/python3.11/site-packages/sklearn/metrics/_ranking.py:1146: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
/grid_mnt/data_cms_upgrade/cuisset/conda/envs/ticlRegression-gpu/lib/python3.11/site-packages/sklearn/metrics/_ranking.py:1146: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
/grid_mnt/data_cms_upgrade/cuisset/conda/envs/ticlRegression-gpu/lib/python3.11/site-packages/sklearn/metrics/_ranking.py:1137: UndefinedMetricWarning: No negative samples in y_true, false positive value should be meaningless
  warnings.warn(
/grid_mnt/data_cms_upgrade/cui

In [11]:
def histedges_equalN(x, nbin):
    npt = len(x)
    return np.interp(np.linspace(0, npt, nbin + 1),
                     np.arange(npt),
                     np.sort(x))
val_etas = val_dataset[:]["features"][0][:, 3] # index 3 is multi_eta
val_energies = val_dataset[:]["features"][0][:, 2] # index 2 is multi_en
ens = histedges_equalN(val_energies, 5)
etas = histedges_equalN(torch.abs(val_etas), 4)
ens, etas

(array([  1.50000608,   2.21427965,   3.11312909,   4.44952669,
          7.04064255, 112.21328735]),
 array([1.52112067, 2.28675771, 2.5121839 , 2.68080544, 3.12905979]))

In [10]:
histedges_equalN(val_energies[val_energies > 7], 4)

array([  7.00000334,   8.19011784,   9.98443699,  13.35840893,
       112.21328735])